notifications:
  email: false
branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-zef
script:
  - export PATH=/home/travis/.rakudobrew/moar-master/install/share/perl6/site/bin:$PATH
  - zef install .
  - 6lib init
  - ls .6lib
